---
title: "Study 1 - Phyloseq"
output: html_document
date: "2025-02-03"
---

```{r}
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")
```

```{r}
md <- readRDS("metadata_1.rds") # metadata load
seqtab <- readRDS("seqtab.nochim_1.rds") # seqtab.nochim
taxa <- readRDS("taxa_1.rds") # genus level taxa
```

```{r}
# make sure rownames and setab rows match
md2 <- md[match(rownames(seqtab), md$Run), ]
rownames(md2) <- md2$Run
```

### some seqtab the sample name have _1, inspecting the object shows no issues

## Create Phyloseq Object
```{r}
ps <- phyloseq(otu_table(seqtab, taxa_are_rows=FALSE), 
               sample_data(md2), 
               tax_table(taxa))
```

## Remove eukaryotes and unassigned phyla
```{r}
ps <- subset_taxa(ps, Kingdom != "Eukaryota")
ps <- subset_taxa(ps, !is.na(Phylum))
```

## Remove samples with less than 500 reads
```{r}
ps_filt <- prune_samples(sample_sums(ps)>=500, ps) 

# Some taxa might have been present only in these low-count samples, so we will make sure to remove taxa that are absent in all samples
ps_filt <- prune_taxa(taxa_sums(ps_filt)>0, ps_filt)
```

```{r}
library(dplyr)
```

### 7.2. Quick peek at data analysis
```{r plot, fig.width = 10, fig.height = 4}
# Absolute abundance
# plot_bar(ps, fill = "Phylum")+ facet_wrap("host_disease", scales="free_x") + theme(axis.text.x = element_blank())

# Relative abundance for Phylum
phylum.table <- ps_filt %>%
  tax_glom(taxrank = "Phylum") %>%                     # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>% # Transform to rel. abundance
  psmelt()                                             # Melt to long format

ggplot(phylum.table, aes(x = reorder(Sample, Sample, function(x) mean(phylum.table[Sample == x & Phylum == 'Firmicutes', 'Abundance'])),
                         y = Abundance, fill = Phylum))+
  facet_wrap(~ Study.Group, scales = "free") + # scales = "free" removes empty lines
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(size = 2, angle = -90))+
  labs(x = "Samples", y = "Relative abundance")
```
```{r}
saveRDS(ps, "ps_1.rds")
saveRDS(ps_filt, "ps_filt_1.rds")
```

